apiVersion: v1
kind: Pod
metadata:
  name: pod-env
spec:
  containers:
    - name: pod-env
      image: busybox:latest
      command: ["sh", "-c", "env |  grep APP_"]
      envFrom:
        - configMapRef:
            name: app-config
