apiVersion: v1
kind: Secret
metadata:
  name: mysql-auth
stringData:
  MYSQL_ROOT_PASSWORD: "admin#capstone"
  MYSQL_DATABASE: "capstone-db"
  MYSQL_USER: "phoenix1"
  MYSQL_PASSWORD: "user#capstone"
