apiVersion: v1
kind: Pod
metadata:
  name: liveness-pod
spec:
  containers:
    - name: liveness-container
      image: busybox:latest
      command:
        [
          "sh",
          "-c",
          "touch /tmp/healthy && sleep 30 && rm -rf /tmp/healthy && sleep 3600",
        ]
      livenessProbe:
        exec:
          command:
            - cat
            - /tmp/healthy
        initialDelaySeconds: 5 # Wait 5 seconds before starting probes
        periodSeconds: 5 # Probe every 5 seconds
        failureThreshold: 3 # Fail after 3 consecutive failed checks
