apiVersion: v1
kind: Pod
metadata:
  name: pending-pod
spec:
  containers:
    - name: heavy-app
      image: nginx:1.25
      resources:
        requests:
          cpu: "100" # Requests 100 full cores!
          memory: "128Gi" # Requests 128 Gigabytes of RAM!
