apiVersion: v1
kind: Pod
metadata:
  name: startup-pod
spec:
  containers:
    - name: slow-app
      image: busybox:latest
      command: ["sh", "-c", "sleep 20 && touch /tmp/started && sleep 3600"]
      startupProbe:
        exec:
          command:
            - cat
            - /tmp/started
        periodSeconds: 5
        failureThreshold: 2 # 5s * 12 = 60 seconds budget to start up!
      livenessProbe:
        exec:
          command:
            - cat
            - /tmp/started
        periodSeconds: 5
